GET http://localhost:5000/users

###
POST http://localhost:5000/users
Content-Type: application/json

{
  "name": "Fahmi 2",
  "email": "email2@gmail.com",
  "password": "123456",
  "confirmPassword": "123457"
}