GET http://localhost:5000/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsIm5hbWUiOiJGYWhtaSIsImVtYWlsIjoiZW1haWxAZ21haWwuY29tIiwiaWF0IjoxNjgxOTM2OTg2LCJleHAiOjE2ODE5MzcwMDZ9.qzBEXKkAUyYjQTHi8IucpAQKSpSmisQFELDVAlvu0Jc

###
POST http://localhost:5000/users
Content-Type: application/json

{
  "name": "Fahmi 2",
  "email": "email2@gmail.com",
  "password": "123456",
  "confirmPassword": "123456"
}

###
POST http://localhost:5000/login
Content-Type: application/json

{
  "email": "email@gmail.com",
  "password": "123456"
}

###
GET http://localhost:5000/token

###
DELETE http://localhost:5000/logout